### ISSUE TITLE
Visualize stocks, sinks, and flows

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#68]
A key aspect of urban environments is that they are in constant motion. Within the urban environment, there are many stocks, sinks, and flows that constitute the urban metabolism. These stocks and flows can come from global sources.

Examples:
- people
- food
- goods/materials
- water
- waste

## Task
- [ ] Research various ways to visualize stocks and flows
- [ ] Document existing examples of visualizations for stocks, sinks, and flows
- [ ] Describe how we might display stocks, sinks, and flows in our design app
