### ISSUE TITLE
Create social accounts for community outreach

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#74]
We want to build a community around this project. We can promote our idea and activities on various social channels.

However, we should be selective about the platforms on which we engage, to prevent from spreading ourselves too thin.

## Task
Create social profiles on the following platforms:
- [x] [YouTube](https://www.youtube.com/channel/UCrV_KSms3BNStyOFAvx4l1w) - for video updates about the progress and meetings
- [x] [OpenCollective](https://opencollective.com/suds) - for transparent fundraising
- [x] [Twitter](https://twitter.com/SustUrbanDesign) - for sharing our progress and participating in the broader discussions
- [X] [Matrix/Riot](https://riot.im/app/#/room/#sud:matrix.org) - for real-time chat among our community members
- [x] Add links to all community channels above in our README and on our website
  - [x] Try using icon buttons for the links for improved user experience

**Comment by MaxThakurCodes** [comment]
We have a youtube, as we have a gmail account setup. I can transfer it over to another service, I just had to get the email setup.

**Comment by MaxThakurCodes** [comment]
@brylie Could you possibly send the links to the services, attached to this message?

**Comment by brylie** [comment]
@MaxThakurCodes I'm sorry to work at cross-purposes. Here are the social profiles I have set up:

- [Twitter](https://twitter.com/SustUrbanDesign)
- [YouTube](https://www.youtube.com/channel/UCrV_KSms3BNStyOFAvx4l1w)
- [OpenCollective](https://opencollective.com/suds)

We don't need a Gmail account, as we have a domain name that can host our own email addresses. 

Let's discuss this task at the next weekly meeting so that we don't get out of sync again :-)

**Comment by brylie** [comment]
@MaxThakurCodes now that we have the social accounts, I am hoping that you will be interested in taking on a role of community steward :-)

**Comment by MaxThakurCodes** [comment]
@brylie I would gladly be willing to take that role and help out with making some videos and things like that.

**Comment by brylie** [comment]
Very cool Max! 

Would you consider making an issue to track progress on creating a simple introduction video for our YouTube channel? Would that be a task that you would be interested in completing?

**Comment by MaxThakurCodes** [comment]
I can't seem to get the Roit/Matrix Badge working with [shields.io](https://shields.io/).

**Comment by brylie** [comment]
https://img.shields.io/badge/Chat-Join%20our%20discussion%20on%20Matrix-green

**Comment by MaxThakurCodes** [comment]
Thanks!
