### ISSUE TITLE
Embedded energy

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#76]
Embedded energy describes how much energy "resides" in materials throughout the urban environment. For example, how much CO2 was used to manufacture and distribute the concrete for a city street?

It might prove useful, yet likely difficult, to provide some way of querying the embedded energy contained in specific urban structures or areas.

## Task
- [ ] **research** the concept of "embedded energy" to locate useful literature
- [ ] **document** your research findings in this project's documentation
- [ ] **describe** how an embedded energy metric might be used in our application
- [ ] **design** one or more hypothetical user interface components for viewing and analyzing embedded energy for a specific structure or selected area
- [ ] **discuss** the hypothetical costs of developing this idea and the potential benefits to end user personas

## Resources
- Wikipedia [embedded energy](https://en.wikipedia.org/wiki/Embodied_energy)
