### ISSUE TITLE
Urban heat island

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#77]
The urban heat island effect describes how urban geometry and material composition affects the local climate. The local climate in turn influences people's health and perception as well as energy consumption.

## Task
- [ ] research the urban heat island effect
- [ ] document your findings and relevant resources
- [ ] describe how urban climate fits in to the urban design process
- [ ] design one or more hypothetical user interfaces for analysing and simulating urban heat island phenomena 
- [ ] discuss the feasibility and relative importance of adding support for urban climate analysis to this project
- [ ] divide and develop - break the task into small chunks and begin development
