### ISSUE TITLE
Walkability and accessibility

### ISSUE THREAD

**Issue by brylie** [SustainableUrbanDesign/app#79]
Walkability indicates how close people are to essential services, such as food, education, and work. Walkability is not just limited to walking, however, and should take into account the accessibility of essential services, routes, as well as proximity.

## Task
- [ ] research the concept of "walkability" (including from the standpoint of accessibility) and common measurements thereof
- [ ] document your findings 
- [ ] describe how a "walkability" metric might be useful to urban planners
- [ ] design one or more hypothetical interfaces for viewing and analysing urban walkability
- [ ] discuss the relative importance of a walkability score in our platform
- [ ] develop a minimum-viable prototype for community feedback
